In [4]:
import pandas as pd
import numpy as np

df=pd.read_csv('diabetes_unclean.csv')

In [5]:
print(df)

       ID  No_Pation Gender   AGE  Urea    Cr  HbA1c  Chol   TG  HDL  LDL  \
0     502      17975      F  50.0   4.7  46.0    4.9   4.2  0.9  2.4  1.4
1     735      34221      M  26.0   4.5  62.0    4.9   3.7  1.4  1.1  2.1
2     420      47975      F  50.0   4.7  46.0    4.9   4.2  0.9  2.4  1.4
3     680      87656      F  50.0   4.7  46.0    4.9   4.2  0.9  2.4  1.4
4     504      34223      M  33.0   7.1  46.0    4.9   4.9  1.0  0.8  2.0
...   ...        ...    ...   ...   ...   ...    ...   ...  ...  ...  ...
1004  191     454316      M  55.0   NaN  62.0    6.8   5.3  2.0  1.0  3.5
1005  192     454316      M  55.0   4.8  88.0    NaN   5.7  4.0  0.9  3.3
1006  193     454316      M  62.0   6.3  82.0    6.7   5.3  2.0  1.0  3.5
1007  194     454316      F  57.0   4.1  70.0    9.3   5.3  3.3  1.0  1.4
1008  195       4543      f  55.0   4.1  34.0   13.9   5.4  1.6  1.6  3.1

      VLDL   BMI CLASS
0      0.5  24.0     N
1      0.6  23.0     N
2      0.5  24.0     N
3      0.5  24.0     N
4      0.4  21.0     N
...    ...   ...   ...
1004   0.9  30.1    Y
1005   1.8  30.0    Y
1006   NaN  30.1    Y
1007   1.3  29.0    Y
1008   0.7  33.0    Y

[1009 rows x 14 columns]

In [6]:
df.isnull().sum()

ID           0
No_Pation    0
Gender       0
AGE          1
Urea         1
Cr           2
HbA1c        3
Chol         2
TG           2
HDL          1
LDL          2
VLDL         1
BMI          0
CLASS        0
dtype: int64

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1009 entries, 0 to 1008
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ID         1009 non-null   int64
 1   No_Pation  1009 non-null   int64
 2   Gender     1009 non-null   object
 3   AGE        1008 non-null   float64
 4   Urea       1008 non-null   float64
 5   Cr         1007 non-null   float64
 6   HbA1c      1006 non-null   float64
 7   Chol       1007 non-null   float64
 8   TG         1007 non-null   float64
 9   HDL        1008 non-null   float64
 10  LDL        1007 non-null   float64
 11  VLDL       1008 non-null   float64
 12  BMI        1009 non-null   float64
 13  CLASS      1009 non-null   object
dtypes: float64(10), int64(2), object(2)
memory usage: 110.5+ KB

In [8]:
df.dtypes

ID             int64
No_Pation      int64
Gender        object
AGE          float64
Urea         float64
Cr           float64
HbA1c        float64
Chol         float64
TG           float64
HDL          float64
LDL          float64
VLDL         float64
BMI          float64
CLASS         object
dtype: object

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df.nunique()

ID           800
No_Pation    961
Gender         3
AGE           49
Urea         110
Cr           113
HbA1c        111
Chol          77
TG            69
HDL           48
LDL           65
VLDL          60
BMI           64
CLASS          5
dtype: int64

In [12]:
df.value_counts('Gender')

Gender
M    570
F    437
f      2
Name: count, dtype: int64

In [13]:
df['Gender'].replace('F','Female')

0       Female
1            M
2       Female
3       Female
4            M
         ...
1004         M
1005         M
1006         M
1007    Female
1008         f
Name: Gender, Length: 1009, dtype: object

In [15]:
df['Gender'].nunique()

3

In [17]:
from sklearn.model_selection import train_test_split

In [20]:
y=df[['CLASS']]
y.shape

(1009, 1)

In [21]:
print(y)

     CLASS
0        N
1        N
2        N
3        N
4        N
...    ...
1004    Y
1005    Y
1006    Y
1007    Y
1008    Y

[1009 rows x 1 columns]

In [26]:
x=df.drop(columns=['ID','No_Pation','CLASS'])
x

     Gender   AGE  Urea    Cr  HbA1c  Chol   TG  HDL  LDL  VLDL   BMI
0         F  50.0   4.7  46.0    4.9   4.2  0.9  2.4  1.4   0.5  24.0
1         M  26.0   4.5  62.0    4.9   3.7  1.4  1.1  2.1   0.6  23.0
2         F  50.0   4.7  46.0    4.9   4.2  0.9  2.4  1.4   0.5  24.0
3         F  50.0   4.7  46.0    4.9   4.2  0.9  2.4  1.4   0.5  24.0
4         M  33.0   7.1  46.0    4.9   4.9  1.0  0.8  2.0   0.4  21.0
...     ...   ...   ...   ...    ...   ...  ...  ...  ...   ...   ...
1004      M  55.0   NaN  62.0    6.8   5.3  2.0  1.0  3.5   0.9  30.1
1005      M  55.0   4.8  88.0    NaN   5.7  4.0  0.9  3.3   1.8  30.0
1006      M  62.0   6.3  82.0    6.7   5.3  2.0  1.0  3.5   NaN  30.1
1007      F  57.0   4.1  70.0    9.3   5.3  3.3  1.0  1.4   1.3  29.0
1008      f  55.0   4.1  34.0   13.9   5.4  1.6  1.6  3.1   0.7  33.0

[1009 rows x 11 columns]

In [40]:
x_train,x_test,y_train,y_test=train_test_split(x,y)

In [39]:
x_train,x_test,y_train,y_test

(    Gender   AGE  Urea     Cr  HbA1c  Chol   TG  HDL  LDL  VLDL   BMI
 724      M  54.0   5.4   68.0    3.0   1.2  0.7  1.0  0.5   1.5  33.0
 951      F  55.0   6.6  168.0    7.0   4.0  NaN  1.0  2.0   1.0  33.0
 837      M  53.0   3.8   59.0   10.9   5.1  3.2  1.8  2.0   1.0  28.0
 815      F  59.0   6.0   28.0   14.6   6.1  4.4  1.2  1.3   2.0  29.0
 252      F  61.0   2.1   23.0    9.9   4.1  4.2  1.2  1.4   1.1  28.0
 ..     ...   ...   ...    ...    ...   ...  ...  ...  ...   ...   ...
 320      M  60.0   6.5   30.0    9.0   5.9  3.4  0.8  3.7   0.5  30.0
 527      M  52.0   4.9   68.0   10.2   5.9  2.9  1.0  3.6   1.3  39.0
 996      M  31.0   3.0   60.0   12.3   4.1  2.2  0.7  2.4  15.4  37.2
 125      F  39.0   3.0   38.0    6.4   4.7  1.3  1.1  3.1   0.6  22.0
 265      F  51.0   2.1   46.0    5.9   4.1  2.7  1.0  2.0   1.2  36.0

 [807 rows x 11 columns],
     Gender   AGE  Urea    Cr  HbA1c  Chol    TG  HDL  LDL  VLDL   BMI
 891      F  56.0   4.0  38.0    7.7   6.1   2.3  1.6  3.6   1.0  26.0
 753      F  68.0   4.2  41.0   11.9   4.0   1.1  2.3  1.1   0.5  30.0
 452      M  63.0   4.3  42.0    9.0   4.2   3.4  0.9  2.0   1.0  26.0
 667      F  61.0   2.5  45.0   11.6   9.7  13.8  1.0  3.1   6.3  33.0
 353      M  55.0   4.6  77.0    6.5   6.0   1.5  1.3  4.1   0.6  30.0
 ..     ...   ...   ...   ...    ...   ...   ...  ...  ...   ...   ...
 31       M  47.0   4.6  55.0    4.3   4.6   0.8  0.9  4.2   4.1  24.0
 315      M  54.0   5.5  69.0   11.0   6.3   6.8  0.7  2.4   3.1  29.0
 193      M  40.0   4.3  72.0    7.0   4.0   1.8  0.9  2.4  12.2  40.0
 384      M  77.0   6.2  99.0    7.2   3.2   1.1  0.8  2.0   0.5  29.0
 307      M  55.0   3.7  93.0    7.2   3.2   1.9  0.6  1.8   0.8  30.0

 [202 rows x 11 columns],
     CLASS
 724     Y
 951     Y
 837     Y
 815     Y
 252     Y
 ..    ...
 320     Y
 527     Y
 996    Y
 125     P
 265     Y

 [807 rows x 1 columns],
     CLASS
 891     Y
 753     Y
 452     Y
 667     Y
 353     Y
 ..    ...
 31      N
 315     Y
 193     Y
 384     Y
 307     Y

 [202 rows x 1 columns])

In [42]:
x_train.shape

(807, 11)

In [45]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=10)

In [46]:
x_train

    Gender   AGE  Urea     Cr  HbA1c  Chol   TG  HDL  LDL  VLDL   BMI
724      M  54.0   5.4   68.0    3.0   1.2  0.7  1.0  0.5   1.5  33.0
951      F  55.0   6.6  168.0    7.0   4.0  NaN  1.0  2.0   1.0  33.0
837      M  53.0   3.8   59.0   10.9   5.1  3.2  1.8  2.0   1.0  28.0
815      F  59.0   6.0   28.0   14.6   6.1  4.4  1.2  1.3   2.0  29.0
252      F  61.0   2.1   23.0    9.9   4.1  4.2  1.2  1.4   1.1  28.0
..     ...   ...   ...    ...    ...   ...  ...  ...  ...   ...   ...
320      M  60.0   6.5   30.0    9.0   5.9  3.4  0.8  3.7   0.5  30.0
527      M  52.0   4.9   68.0   10.2   5.9  2.9  1.0  3.6   1.3  39.0
996      M  31.0   3.0   60.0   12.3   4.1  2.2  0.7  2.4  15.4  37.2
125      F  39.0   3.0   38.0    6.4   4.7  1.3  1.1  3.1   0.6  22.0
265      F  51.0   2.1   46.0    5.9   4.1  2.7  1.0  2.0   1.2  36.0

[807 rows x 11 columns]